### PR TITLE
Removing "using namespace std;"

### PR DESCRIPTION
**Pull request by waifod**

### CODE REVIEW

**Comment by david-alvarez-rosa** [comment]
Did you even test it once? I'm surprise that this is working TBH.

**Comment by waifod** [comment]
Yes, I did run the main after recompiling.

**Comment by david-alvarez-rosa** [comment]
Cool, @Waifod, thank you for skipping the standard process bypassing our own setup mechanism. Definitely. Well done.

**Comment by waifod** [comment]
Any time, broski :*

**Pull request merged**
