### PR TITLE
Build first working CLI application with some parameters

### PR DESCRIPTION
**Pull request by david-alvarez-rosa**
❯ ./build/quant_finance_models --help
    Quant Finance Models (QFM) CLI utility:
      -h [ --help ]             print usage message
      -a [ --asset ] arg        asset ticket
      -e [ --expiration ] arg   expiration date
      -s [ --strike-price ] arg strike price

### CODE REVIEW

**Comment by david-alvarez-rosa** [comment]
@Waifod—can you review this one?  Was a bit left opened; it's first step towards a CLI application.

**Comment by waifod** [comment]
I wanted to first discuss in person what to include, but it's fine to have a starting sample.

**Review by waifod — APPROVED** [review]
Thanks! Approving and merging.

**Comment by waifod** [comment]
There are problems with the formatting *ops*

**Comment by david-alvarez-rosa** [comment]
Thanks for fixing!

**Pull request merged**
